name := "CensusProject"
version := "1.0"
scalaVersion := "2.10.4"
libraryDependencies += "org.scalatest" % "scalatest_2.10" % "1.9.1" % "test"
libraryDependencies += "org.mockito" % "mockito-all" % "1.8.4"